export type KoreanPoemTheme = "comfort" | "hope" | "love" | "reflection" | "nature" | "courage";
export type KoreanPoemOrigin = "all" | "korean" | "world";

export interface KoreanPoemItem {
  id: string;
  title: string;
  titleOriginal?: string;
  poet: string;
  poetOriginal?: string;
  excerpt: string;
  whyRecommended: string;
  theme: KoreanPoemTheme;
  themeLabel: string;
  siyoilUrl: string;
  poemSourceName: string;
  origin?: "korean" | "world";
  country?: string;
}

export const KOREAN_POEM_ORIGINS: Array<{ id: "all" | "korean" | "world"; label: string; icon: string }> = [
  { id: "all", label: "전체 명시", icon: "📚" },
  { id: "korean", label: "한국 명시", icon: "🇰🇷" },
  { id: "world", label: "세계 명시", icon: "🌍" },
];

export const KOREAN_POEM_THEMES: Array<{ id: KoreanPoemTheme; label: string; icon: string }> = [
  { id: "comfort", label: "위로와 치유", icon: "🌿" },
  { id: "love", label: "사랑과 그리움", icon: "💌" },
  { id: "hope", label: "희망과 용기", icon: "✨" },
  { id: "reflection", label: "자아와 성찰", icon: "🪞" },
  { id: "nature", label: "자연과 평온", icon: "🍃" },
  { id: "courage", label: "열정과 기개", icon: "🔥" },
];

export const KOREAN_FAMOUS_POEMS: KoreanPoemItem[] = [
  {
    id: "seosi",
    title: "서시(序詩)",
    titleOriginal: "서시",
    poet: "윤동주 (대한민국)",
    poetOriginal: "윤동주",
    excerpt: "죽는 날까지 하늘을 우러러\n한 점 부끄럼이 없기를,\n잎새에 이는 바람에도\n나는 괴로워했다.\n별을 노래하는 마음으로\n모든 죽어가는 것을 사랑해야지\n그리고 나한테 주어진 길을\n걸어가야겠다.\n\n오늘 밤에도 별이 바람에 스치운다.",
    whyRecommended: "순결한 양심과 맑은 자아를 비추어 보며, 흔들리는 일상 속에서도 곧고 맑은 중심을 세우도록 이끕니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=405&subcontentid=25164",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "byeol_heneun_bam",
    title: "별 헤는 밤",
    titleOriginal: "별 헤는 밤",
    poet: "윤동주 (대한민국)",
    poetOriginal: "윤동주",
    excerpt: "계절이 지나가는 하늘에는\n가을로 가득 차 있습니다.\n\n나는 아무 걱정도 없이\n가을 속의 별들을 다 헤일 듯합니다.\n\n가슴 속에 하나 둘 새겨지는 별을\n이제 다 못 헤는 것은\n쉬이 아침이 오는 까닭이요,\n내일 밤이 남은 까닭이요,\n아직 나의 청춘이 다하지 않은 까닭입니다.\n\n별 하나에 추억과\n별 하나에 사랑과\n별 하나에 쓸쓸함과\n별 하나에 동경과\n별 하나에 시와\n별 하나에 어머니, 어머니",
    whyRecommended: "아름다운 밤하늘의 별들 속에 새겨진 그리움과 이상, 영원히 퇴색하지 않는 순수한 시심을 일깨워 줍니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=405&subcontentid=25165",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "jahwasang",
    title: "자화상(自畵像)",
    titleOriginal: "자화상",
    poet: "윤동주 (대한민국)",
    poetOriginal: "윤동주",
    excerpt: "산모퉁이를 돌아 논가 외딴 우물을 홀로 찾아가선\n가만히 들여다봅니다.\n\n우물 속에는 달이 밝고 구름이 흐르고 하늘이 펼치고\n파아란 바람이 불고 가을이 있습니다.\n\n그리고 한 사나이가 있습니다.\n어쩐지 그 사나이가 미워져 돌아갑니다.\n\n돌아가다 생각하니 그 사나이가 가엾어집니다.\n도로 가 들여다보니 사나이는 그대로 있습니다.",
    whyRecommended: "우물 속 자신을 미워하다가도 다시 가엾어하며 스스로를 품어 안는 따뜻한 자기 화해의 여정을 선물합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=405&subcontentid=25166",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "saeroun_gil",
    title: "새로운 길",
    titleOriginal: "새로운 길",
    poet: "윤동주 (대한민국)",
    poetOriginal: "윤동주",
    excerpt: "내를 건너서 숲으로\n고개를 넘어서 마을로\n\n어제도 가고 오늘도 갈\n나의 길 새로운 길\n\n민들레가 피고 까치가 날고\n아가씨가 지나고 바람이 일고\n\n나의 길은 언제나 새로운 길\n오늘도…… 내일도……\n\n내를 건너서 숲으로\n고개를 넘어서 마을로",
    whyRecommended: "어떤 시련 앞에서도 멈추지 않고 묵묵히 자신의 새로운 길을 걸어가는 희망의 걸음을 북돋웁니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=405&subcontentid=25167",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "swipge_sseu-yeojin_si",
    title: "쉽게 씌어진 시",
    titleOriginal: "쉽게 씌어진 시",
    poet: "윤동주 (대한민국)",
    poetOriginal: "윤동주",
    excerpt: "창밖에 밤비가 속살거려\n육첩방은 남의 나라,\n\n시인이란 슬픈 천명인 줄 알면서도\n한 줄 시를 적어 볼까,\n\n인생은 살기 어렵다는데\n시가 이렇게 쉽게 씌어지는 것은\n부끄러운 일이다.\n\n등불을 밝혀 어둠을 조금 내몰고,\n시대처럼 올 아침을 기다리는 최후의 나,\n\n나는 나에게 작은 손을 내밀어\n눈물과 위안으로 잡는 최초의 악수.",
    whyRecommended: "어둠 속에서도 등불을 밝히며 새로운 아침을 예비하는 창작자의 숭고한 지성과 진솔한 내면을 마주합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=405&subcontentid=25168",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nawa_natasya",
    title: "나와 나타샤와 흰 당나귀",
    titleOriginal: "나와 나타샤와 흰 당나귀",
    poet: "백석 (대한민국)",
    poetOriginal: "백석",
    excerpt: "가난한 내가\n아름다운 나타샤를 사랑해서\n오늘밤은 푹푹 눈이 나린다\n\n나타샤를 사랑은 하고\n눈은 푹푹 날리고\n나는 혼자 쓸쓸히 앉어 소주를 마신다\n소주를 마시며 생각한다\n나타샤와 나는\n눈이 푹푹 쌓이는 밤 흰 당나귀 타고\n산골로 가자 마가리에 살자\n\n눈은 푹푹 나리고\n아름다운 나타샤는 나를 사랑하고\n어디서 흰 당나귀도 오늘밤이 좋아서 응앙응앙 울을 것이다",
    whyRecommended: "세속의 소란을 벗어나 가장 순결하고 아름다운 눈 내리는 밤의 낭만과 지고지순한 사랑으로 초대합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=510&subcontentid=31201",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "namsiniju_yudong",
    title: "남신의주 유동 박시봉방(南新義州 柳洞 朴時逢方)",
    titleOriginal: "남신의주 유동 박시봉방",
    poet: "백석 (대한민국)",
    poetOriginal: "백석",
    excerpt: "어느 사이에 나는 아내도 없고, 또,\n아내와 같이 살던 집도 없어지고,\n그리고 살뜰한 부모며 동생들과도 멀리 떨어져서,\n그 어느 바람 세인 쓸쓸한 거리 끝에 헤매이었다.\n\n그러나 잠시 뒤에 나는 고개를 들어,\n허옇게 눈을 덮어쓴 문창을 바라보며,\n그물그물 어두워 가는 하늘을 생각하고,\n저 머나먼 산 옆에 눈을 맞고 꼿꼿이 서 있는,\n굳고 정한 갈매나무라는 나무를 생각하는 것이었다.",
    whyRecommended: "처절한 고독과 결핍 속에서도 의연히 눈을 맞고 서 있는 갈매나무처럼, 내면의 고결한 존엄을 회복시켜 줍니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=510&subcontentid=31202",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "yeoseung",
    title: "여승(女僧)",
    titleOriginal: "여승",
    poet: "백석 (대한민국)",
    poetOriginal: "백석",
    excerpt: "여승은 합장하고 절을 했다.\n가지취의 내음새가 났다.\n쓸쓸한 낯이 옛날같이 늙었다.\n나는 불경처럼 서러워졌다.\n\n평안도의 어느 산 깊은 금점판\n나는 파리한 여인에게서 옥수수를 샀다.\n여인은 나이 어린 딸아이를 따리며 가을밤같이 차게 울었다.\n\n산꿩도 설게 울은 슬픈 날이 있었다.\n산절의 마당귀에 여인의 머리오리가\n눈물방울과 같이 떨어진 날이 있었다.",
    whyRecommended: "삶의 기구한 비애를 깊고 그윽한 연민의 시선으로 어루만지며 영혼의 깊은 정화를 선사합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=510&subcontentid=31203",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "guksu",
    title: "국수",
    titleOriginal: "국수",
    poet: "백석 (대한민국)",
    poetOriginal: "백석",
    excerpt: "눈이 많이 와서\n산골 길은 끊어지고 눈더미에 묻힌 집에서\n꿩 사냥꾼들이 꿩을 잡아 오고\n\n이것은 그 조용한 하늘가 마을에\n겨울밤 눈이 하얗게 쌓이면\n어른들이 삼삼오오 모여 반가이 맞아 먹는\n희고 부드럽고 구수한 것\n\n아, 이 반가운 것은 무엇인가\n이 히수무레하고 부드럽고 수수하고 슴슴한 것은 무엇인가",
    whyRecommended: "소박한 고향의 정취와 따스한 인간미가 서린 겨울밤의 온기로 얼어붙은 마음을 녹여줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=510&subcontentid=31204",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "jindallaekkot",
    title: "진달래꽃",
    titleOriginal: "진달래꽃",
    poet: "김소월 (대한민국)",
    poetOriginal: "김소월",
    excerpt: "나 보기가 역겨워\n가실 때에는\n말없이 고이 보내 드리우리다\n\n영변에 약산\n진달래꽃\n아름 따다 가실 길에 뿌리우리다\n\n가시는 걸음 걸음\n놓인 그 꽃을\n사뿐히 즈려밟고 가시옵소서\n\n나 보기가 역겨워\n가실 때에는\n죽어도 아니 눈물 흘리우리다",
    whyRecommended: "한국 서정시의 정수로서, 슬픔을 승화하여 축복으로 바꾸는 역설적 사랑의 미학을 전합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=10&subcontentid=612",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "sanyuhwa",
    title: "산유화(山有花)",
    titleOriginal: "산유화",
    poet: "김소월 (대한민국)",
    poetOriginal: "김소월",
    excerpt: "산에는 꽃 피네\n꽃이 피네\n갈 봄 여름 없이\n꽃이 피네\n\n산에\n산에\n피는 꽃은\n저만치 혼자서 피어 있네\n\n산에서 우는 작은 새여\n꽃이 좋아\n산에서\n우노라네\n\n산에는 꽃 지네\n꽃이 지네\n갈 봄 여름 없이\n꽃이 지네",
    whyRecommended: "대자연의 무심한 순환과 존재의 고독을 맑고 담담한 가락으로 노래하며 마음에 깊은 쉼을 줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=10&subcontentid=613",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "eommaya_nunaya",
    title: "엄마야 누나야",
    titleOriginal: "엄마야 누나야",
    poet: "김소월 (대한민국)",
    poetOriginal: "김소월",
    excerpt: "엄마야 누나야 강변 살자,\n뜰에는 반짝이는 금모래 빛,\n뒷문 밖에는 갈잎의 노래,\n엄마야 누나야 강변 살자.",
    whyRecommended: "평화롭고 순수한 고향 강변의 풍경을 통해 유년의 따스한 안식처로 마음을 안내합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=10&subcontentid=614",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "chohon",
    title: "초혼(招魂)",
    titleOriginal: "초혼",
    poet: "김소월 (대한민국)",
    poetOriginal: "김소월",
    excerpt: "산산이 부서진 이름이여!\n허공 중에 헤어진 이름이여!\n불러도 주인 없는 이름이여!\n부르다가 내가 죽을 이름이여!\n\n심중에 남아 있는 말 한마디는\n끝끝내 마저 하지 못하였구나.\n사랑하던 그 사람이여!\n사랑하던 그 사람이여!",
    whyRecommended: "가슴 터질 듯한 절규와 열정의 카타르시스를 통해 마음에 맺힌 슬픔을 쏟아내고 정화하게 합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=10&subcontentid=615",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "meon_huil",
    title: "먼 후일",
    titleOriginal: "먼 후일",
    poet: "김소월 (대한민국)",
    poetOriginal: "김소월",
    excerpt: "먼 훗날 당신이 찾으시면\n그때에 내 말이 '잊었노라'\n\n당신이 속으로 나무라면\n'무척 그리다가 잊었노라'\n\n그래도 당신이 나무라면\n'믿기지 않아서 잊었노라'\n\n오늘도 어제도 아니 잊고\n먼 훗날 그때에 '잊었노라'",
    whyRecommended: "잊으려 할수록 더욱 선명해지는 잊지 못할 사랑의 진실을 재치와 애절함으로 노래합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=10&subcontentid=616",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "hyangsu",
    title: "향수(鄕愁)",
    titleOriginal: "향수",
    poet: "정지용 (대한민국)",
    poetOriginal: "정지용",
    excerpt: "넓은 벌 동쪽 끝으로\n옛이야기 지줄대는 실개천이 휘돌아 나가고,\n얼룩백이 황소가 해설피 금빛 게으른 울음을 우는 곳,\n―― 그곳이 차마 꿈엔들 잊힐 리야.\n\n질화로에 재가 식어지면\n비인 밭에 밤바람 소리 말을 달리고,\n엷은 졸음에 겨운 늙으신 아버지가 짚베개를 돋아 고이시는 곳,\n―― 그곳이 차마 꿈엔들 잊힐 리야.",
    whyRecommended: "한국어의 가장 감각적인 음악성과 고향에 대한 원초적 그리움을 한 폭의 수채화처럼 펼쳐 보입니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=396&subcontentid=24601",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "hosu_1",
    title: "호수 1",
    titleOriginal: "호수 1",
    poet: "정지용 (대한민국)",
    poetOriginal: "정지용",
    excerpt: "얼굴 하나야\n손바닥 둘로\n폭 가리지만,\n\n보고픈 마음\n호수만 하니\n눈감을 밖에.",
    whyRecommended: "간결한 여섯 줄 안에 우주보다 넓은 그리움의 깊이를 압축해 낸 절묘한 서정의 극치입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=396&subcontentid=24605",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "yurichang_1",
    title: "유리창 1",
    titleOriginal: "유리창 1",
    poet: "정지용 (대한민국)",
    poetOriginal: "정지용",
    excerpt: "유리에 차고 슬픈 것이 어른거린다.\n열없이 붙어서서 입김을 흐리우니\n길들은 양 언 날개를 다파거린다.\n\n지우고 보고 지우고 보아도\n새까만 밤이 밀려 나가고 밀려와 부딪히고,\n물먹은 별이, 반짝, 보석처럼 박힌다.\n\n밤에 홀로 유리를 닦는 것은\n외로운 황홀한 심사이어니.",
    whyRecommended: "투명한 유리창을 사이에 둔 만남과 이별, 차가운 슬픔 속에서도 보석처럼 빛나는 감각적 언어를 선사합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=396&subcontentid=24608",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "chunseol",
    title: "춘설(春雪)",
    titleOriginal: "춘설",
    poet: "정지용 (대한민국)",
    poetOriginal: "정지용",
    excerpt: "문 열자 선뜻!\n먼 산이 이마에 차라.\n\n우수절 들어\n바로 초하루 아침,\n\n새삼스레 눈이 덮인 뫼뿌리와\n서늘옵고 빛난 이마받이 하다.\n\n얼음 금 가고 바람 새로 따르거니\n흰 옷고름 절로 향그럽호라.",
    whyRecommended: "봄을 앞두고 내린 맑고 차가운 눈처럼, 머리와 감각을 서늘하고 맑게 깨워주는 청신한 기운을 전합니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=396&subcontentid=24612",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "moran-i_pigikkajineun",
    title: "모란이 피기까지는",
    titleOriginal: "모란이 피기까지는",
    poet: "김영랑 (대한민국)",
    poetOriginal: "김영랑",
    excerpt: "모란이 피기까지는\n나는 아직 나의 봄을 기다리고 있을 테요\n모란이 뚝뚝 떨어져 버린 날\n나는 비로소 봄을 여읜 설움에 잠길 테요\n\n오월 어느 날, 그 하루 무덥던 날\n떨어져 누운 꽃잎마저 시들어 버리고는\n천지에 모란은 자취도 없어지고\n\n모란이 피기까지는\n나는 아직 기다리고 있을 테요, 찬란한 슬픔의 봄을",
    whyRecommended: "기다림의 찬란함과 슬픔조차도 아름다움으로 끌어안는 한국 순수 서정시의 극치를 보여줍니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=345&subcontentid=21401",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "doldam-e_soksag-ineun",
    title: "돌담에 속삭이는 햇발",
    titleOriginal: "돌담에 속삭이는 햇발",
    poet: "김영랑 (대한민국)",
    poetOriginal: "김영랑",
    excerpt: "돌담에 속삭이는 햇발같이\n풀 아래 웃음 짓는 샘물같이\n내 마음 고요히 고운 봄 길 위에\n오늘 하루 따스한 시의 옷을 입히련다\n\n바다에 춤추는 윤슬같이\n하늘에 떠도는 실구름같이\n살포시 흔들리는 아침의 숨결 속에\n맑고 고운 노래를 띄우련다",
    whyRecommended: "보드라운 봄 햇살처럼 지친 일상을 포근하게 감싸주는 온화하고 맑은 언어의 축복입니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=345&subcontentid=21405",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nim-ui_chimmuk",
    title: "님의 침묵(沈默)",
    titleOriginal: "님의 침묵",
    poet: "한용운 (대한민국)",
    poetOriginal: "한용운",
    excerpt: "님은 갔습니다. 아아, 사랑하는 나의 님은 갔습니다.\n푸른 산빛을 깨치고 단풍나무 숲을 향하여 난 작은 길을 걸어서, 차마 떨치고 갔습니다.\n\n그러나 이별을 쓸데없는 눈물의 원천을 만들고 마는 것은 스스로 사랑을 깨치는 것인 줄 아는 까닭에,\n걷잡을 수 없는 슬픔의 힘을 옮겨서 새 희망의 정수박이에 들어부었습니다.\n\n우리는 만날 때에 떠날 것을 염려하는 것과 같이, 떠날 때에 다시 만날 것을 믿습니다.\n아아, 님은 갔지마는 나는 님을 보내지 아니하였습니다.",
    whyRecommended: "상실과 절망의 비극을 새로운 희망과 부활의 거대한 에너지로 전환하는 위대한 정신의 승리를 보여줍니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=120&subcontentid=7501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "al_su_eopseoyo",
    title: "알 수 없어요",
    titleOriginal: "알 수 없어요",
    poet: "한용운 (대한민국)",
    poetOriginal: "한용운",
    excerpt: "바람도 없는 공중에 수직의 파문을 내이며 고요히 떨어지는 오동잎은 누구의 발자취입니까?\n지리한 장마 끝에 서풍에 몰려가는 무서운 검은 구름의 터진 틈으로, 언뜻언뜻 보이는 푸른 하늘은 누구의 얼굴입니까?\n\n타고 남은 재가 다시 기름이 됩니다. 그칠 줄을 모르고 타는 나의 가슴은 누구의 밤을 지키는 약한 등불입니까?",
    whyRecommended: "신비로운 우주의 섭리와 끝없는 헌신의 마음에 깃든 영원한 사랑의 질문을 던집니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=120&subcontentid=7503",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "inyeonseol",
    title: "인연설(因緣說)",
    titleOriginal: "인연설",
    poet: "한용운 (대한민국)",
    poetOriginal: "한용운",
    excerpt: "함께 영원히 있을 수 없음을 슬퍼 말고\n잠시라도 함께 있을 수 있음을 기뻐하고\n\n좋아해 주지 않음을 노여워 말고\n이만큼 좋아해 주는 것에 만족하고\n나만 애태운다 원망치 말라.\n\n사랑은 주는 것만큼 아름답고\n마음은 비우는 것만큼 가득 차나니.",
    whyRecommended: "관계의 집착과 불안을 내려놓고 현재 함께하는 인연의 소중함에 감사하도록 마음의 닻을 내려줍니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=120&subcontentid=7509",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "gwang-ya",
    title: "광야(曠野)",
    titleOriginal: "광야",
    poet: "이육사 (대한민국)",
    poetOriginal: "이육사",
    excerpt: "까마득한 날에\n하늘이 처음 열리고\n어디 닭 우는 소리 들렸으랴.\n\n모든 산맥들이\n바다를 연모해 휘달릴 때도\n차마 이곳을 범하던 못하였으리라.\n\n지금 눈 내리고\n매화 향기 홀로 아득하니\n내 여기 가난한 노래의 씨를 뿌려라.\n\n다시 천고의 뒤에\n백마 타고 오는 초인이 있어\n이 광야에서 목놓아 부르게 하리라.",
    whyRecommended: "아득한 시공간을 꿰뚫는 웅혼한 기개와, 혹한 속에서도 역사의 새벽을 믿는 불굴의 의지를 전합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=480&subcontentid=29501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "cheongpodo",
    title: "청포도(靑葡萄)",
    titleOriginal: "청포도",
    poet: "이육사 (대한민국)",
    poetOriginal: "이육사",
    excerpt: "내 고장 칠월은\n청포도가 익어 가는 시절.\n\n이 마을 전설이 주저리주저리 열리고\n먼 데 하늘이 꿈꾸며 알알이 들어와 박혀,\n\n내가 바라는 손님은 고달픈 몸으로\n청포를 입고 찾아온다고 했으니,\n\n내 그를 맞아 이 포도를 따 먹으면\n두 손은 함뿍 적셔도 좋으련.\n\n아이야, 우리 식탁엔 은쟁반에\n하이얀 모시 수건을 마련해 두렴.",
    whyRecommended: "청량한 여름날의 푸른 색채와 정갈한 기다림, 평화로운 해후를 예비하는 희망의 설렘을 노래합니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=480&subcontentid=29502",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "jeoljeong",
    title: "절정(絶頂)",
    titleOriginal: "절정",
    poet: "이육사 (대한민국)",
    poetOriginal: "이육사",
    excerpt: "매운 계절의 채찍에 내몰려\n마침내 북방으로 휩쓸려 오다.\n\n하늘도 그만 지쳐 끝난 고원\n서릿발 칼날진 그 위에 서다.\n\n어디다 무릎을 꿇어야 하나\n한 발 재겨 디딜 곳조차 없다.\n\n이러매 눈 감아 생각해 볼밖에\n겨울은 강철로 된 무지갠가 보다.",
    whyRecommended: "극한의 위기 속에서도 비장미를 초월하여 정신의 무지개를 피워 올리는 결연한 용기를 불어넣습니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=480&subcontentid=29503",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nageune",
    title: "나그네",
    titleOriginal: "나그네",
    poet: "박목월 (대한민국)",
    poetOriginal: "박목월",
    excerpt: "강나루 건너서\n밀밭 길을\n\n구름에 달 가듯\n가는 나그네\n\n길은 외줄기\n남도 삼백 리\n\n술 익는 마을마다\n타는 저녁놀\n\n구름에 달 가듯\n가는 나그네",
    whyRecommended: "세상사에 얽매이지 않고 바람처럼 유유자적 흐르는 나그네의 달관과 서정적 풍류를 선사합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=310&subcontentid=19101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "cheongnoru",
    title: "청노루",
    titleOriginal: "청노루",
    poet: "박목월 (대한민국)",
    poetOriginal: "박목월",
    excerpt: "머언 산 청운사\n낡은 기와집\n\n산은 자하산\n봄눈 녹으면\n\n느릅나무\n싹트는 봄 길에\n\n청노루\n맑은 눈에\n\n도는 구름.",
    whyRecommended: "맑고 투명한 청노루의 눈망울처럼, 때 묻지 않은 자연의 순결함이 마음을 깨끗이 씻어내 줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=310&subcontentid=19103",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "ibyeolga",
    title: "이별가",
    titleOriginal: "이별가",
    poet: "박목월 (대한민국)",
    poetOriginal: "박목월",
    excerpt: "뭐락카노, 저편 강기슭에서\n니 뭐락카노, 바람에 불려서\n\n오냐, 오냐, 오냐,\n이승 아니더라도\n저승 가서라도\n\n바람에 불려서 안 들리지만,\n흰 옷자락 펄럭이며\n손짓하는 너의 그 목소리.",
    whyRecommended: "생과 사의 강을 건너뛰는 절절한 이별의 한과, 영원을 잇는 질박한 사랑의 부름을 들려줍니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=310&subcontentid=19107",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "seungmu",
    title: "승무(僧舞)",
    titleOriginal: "승무",
    poet: "조지훈 (대한민국)",
    poetOriginal: "조지훈",
    excerpt: "얇은 사 하이얀 고깔은\n접어서 매만진 고깔이어라.\n\n파르라니 깎은 머리\n박사 고깔에 감추오고,\n\n두 볼에 흐르는 빛이\n정작으로 고와서 서러워라.\n\n빈 대에 황촉불이 말없이 녹는 밤에\n오동잎 잎새마다 달이 지는데,\n\n소매는 길어서 공중에 날리고\n꽃가루 붉게 가리어라.\n\n세사에 시달려도 번뇌는 별빛이라.",
    whyRecommended: "인간 세상의 번뇌와 고통을 찬란한 예술적 춤사위와 영적 정화로 승화시키는 동양 미학의 정점입니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=325&subcontentid=20101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nakhwa",
    title: "낙화(落花)",
    titleOriginal: "낙화",
    poet: "조지훈 (대한민국)",
    poetOriginal: "조지훈",
    excerpt: "꽃이 지기로소니\n바람을 탓하랴\n\n주렴 밖에 성긴 별이\n하나 둘 스러지고\n\n귀촉도 울음 뒤에\n머언 산이 다가서다\n\n촛불을 꺼야 하리\n꽃이 지는데\n꽃 지는 그림자\n뜰에 어리어\n하얀 방안이 어스름 밝아오누나",
    whyRecommended: "피고 지는 자연의 섭리를 관조하며, 스러지는 것들에 대한 고요한 예찬과 깊은 평화를 건넵니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=325&subcontentid=20105",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "hae",
    title: "해",
    titleOriginal: "해",
    poet: "박두진 (대한민국)",
    poetOriginal: "박두진",
    excerpt: "해야 솟아라. 해야 솟아라. 말갛게 씻은 얼굴 고운 해야 솟아라.\n산 넘어서 밤새도록 어둠을 살라 먹고, 이글이글 앳된 얼굴 고운 해야 솟아라.\n\n달밤이 싫여, 달밤이 싫여, 눈물 같은 골짜기에 달밤이 싫여,\n아무도 없는 뜰에 달밤이 나는 싫여……\n\n해야, 고운 해야, 늬가 오면 늬가사 오면,\n나는 나는 청산이 좋아라. 훨훨훨 깃을 치는 청산이 좋아라.",
    whyRecommended: "모든 어둠과 악을 태워버리고 새 세상을 여는 태양의 폭발적인 생명력과 축제의 함성을 전합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=315&subcontentid=19501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "gukhwa_yeop-eseo",
    title: "국화 옆에서",
    titleOriginal: "국화 옆에서",
    poet: "서정주 (대한민국)",
    poetOriginal: "서정주",
    excerpt: "한 송이의 국화꽃을 피우기 위해\n봄부터 소쩍새는\n그렇게 울었나 보다.\n\n한 송이의 국화꽃을 피우기 위해\n천둥은 먹구름 속에서\n또 그렇게 울었나 보다.\n\n그립고 아쉬움에 가슴 조이던\n머언 먼 젊음의 뒤안길에서\n인제는 돌아와 거울 앞에 선\n내 누님같이 생긴 꽃이여.\n\n노오란 네 꽃잎이 피려고\n간밤엔 무서리가 저리 내리고\n내게는 잠도 오지 않았나 보다.",
    whyRecommended: "시련과 인고의 세월을 견뎌낸 뒤에야 비로소 도달하는 원숙하고 그윽한 삶의 아름다움을 일깨웁니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=440&subcontentid=27101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "kkot",
    title: "꽃",
    titleOriginal: "꽃",
    poet: "김춘수 (대한민국)",
    poetOriginal: "김춘수",
    excerpt: "내가 그의 이름을 불러 주기 전에는\n그는 다만\n하나의 몸짓에 지나지 않았다.\n\n내가 그의 이름을 불러 주었을 때\n그는 나에게로 와서\n꽃이 되었다.\n\n내가 그의 이름을 불러 준 것처럼\n나의 이 빛깔과 향기에 알맞는\n누가 나의 이름을 불러 다오.\n그에게로 가서 나도\n그의 꽃이 되고 싶다.\n\n우리들은 모두\n무엇이 되고 싶다.\n너는 나에게 나는 너에게\n잊혀지지 않는 하나의 눈짓이 되고 싶다.",
    whyRecommended: "진정한 명명과 관계 맺음을 통해 무의미한 일상에 빛나는 의미와 사랑의 생명을 불어넣습니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=502&subcontentid=30510",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "chagall-ui_maeul",
    title: "샤갈의 마을에 내리는 눈",
    titleOriginal: "샤갈의 마을에 내리는 눈",
    poet: "김춘수 (대한민국)",
    poetOriginal: "김춘수",
    excerpt: "샤갈의 마을에는 3월에 눈이 온다.\n봄을 바라고 섰는 사나이의 관자놀이에\n새로 돋은 정맥이\n바르르 떤다.\n\n바르르 떠는 사나이의 관자놀이에\n새로 돋은 정맥을 어루만지며\n눈은 수천수만의 날개를 달고\n하늘에서 내려와 샤갈의 마을의\n지붕과 굴뚝을 덮는다.\n\n3월에 눈이 오면\n샤갈의 마을의 쥐똥만 한 겨울 열매들은\n다시 올리브빛으로 물이 들고\n밤에 아낙들은\n그해의 제일 아름다운 불을 켠다.",
    whyRecommended: "회화적 상상력과 맑고 신선한 감각이 교차하며 봄의 태동을 예고하는 신비로운 서정을 선사합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=502&subcontentid=30512",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "pul",
    title: "풀",
    titleOriginal: "풀",
    poet: "김수영 (대한민국)",
    poetOriginal: "김수영",
    excerpt: "풀이 눕는다\n비를 몰아오는 동풍에 나부껴\n풀은 눕고\n드디어 울었다\n날이 흐려서 더 울다가\n다시 누웠다\n\n풀이 눕는다\n바람보다도 더 빨리 눕는다\n바람보다도 더 빨리 울고\n바람보다 먼저 일어난다\n\n날이 흐리고 풀이 눕는다\n발목까지\n발밑까지 눕는다\n바람보다 늦게 누워도\n바람보다 먼저 일어나고\n바람보다 늦게 울어도\n바람보다 먼저 웃는다\n날이 흐리고 풀뿌리가 눕는다",
    whyRecommended: "억압과 고난 속에서도 꺾이지 않고 가장 먼저 일어서는 끈질긴 민초의 생명력을 노래합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=490&subcontentid=30101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nun",
    title: "눈",
    titleOriginal: "눈",
    poet: "김수영 (대한민국)",
    poetOriginal: "김수영",
    excerpt: "눈은 살아 있다\n떨어진 눈은 살아 있다\n마당 위에 떨어진 눈은 살아 있다\n\n기침을 하자\n젊은 시인이여 기침을 하자\n눈 위에 대고 기침을 하자\n눈더러 보라고 마음 놓고 마음 놓고\n기침을 하자\n\n눈은 살아 있다\n죽음을 잊어버린 영혼과 육체를 위하여\n눈은 새벽이 지나도록 살아 있다",
    whyRecommended: "불순한 일상의 찌꺼기를 털어내고 순수한 백설 앞에서 양심의 정직함을 회복하라는 단호한 격려를 건넵니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=490&subcontentid=30102",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "pokpo",
    title: "폭포",
    titleOriginal: "폭포",
    poet: "김수영 (대한민국)",
    poetOriginal: "김수영",
    excerpt: "폭포는 곧은 절벽을 무서운 기색도 없이 떨어진다\n\n규정할 수 없는 물결이\n무엇을 향하여 떨어진다는 의미도 없이\n계절과 주야를 가리지 않고\n고매한 정신처럼 쉴 사이 없이 떨어진다\n\n금잔화도 인가도 보이지 않는 밤이 되면\n폭포는 곧은 소리를 내며 떨어진다\n곧은 소리는 곧은 소리이다\n곧은 소리는 소리를 부른다\n\n번개와 같이 떨어지는 물방울은\n취할 순간조차 마음에 주지 않고\n나타와 안정을 뒤집어 놓은 듯이\n높이도 폭도 없이\n떨어진다",
    whyRecommended: "안주와 타협을 거부하고 거침없이 수직 낙하하는 폭포처럼, 타협 없는 자유와 비판 정신을 각성시킵니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=490&subcontentid=30103",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "gwicheon",
    title: "귀천(歸天)",
    titleOriginal: "귀천",
    poet: "천상병 (대한민국)",
    poetOriginal: "천상병",
    excerpt: "나 하늘로 돌아가리라.\n새벽빛 와 닿으면 스러지는\n이슬 더불어 손에 손을 잡고,\n\n나 하늘로 돌아가리라.\n노을빛 함께 단둘이서\n기슭에서 놀다가 구름 손짓하며는,\n\n나 하늘로 돌아가리라.\n아름다운 이 세상 소풍 끝내는 날,\n가서, 아름다웠더라고 말하리라……",
    whyRecommended: "모진 가난과 고초 속에서도 세상을 '아름다운 소풍'으로 품어 안은 성자 같은 순수와 초탈을 전합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=560&subcontentid=34501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "sae_cheonsangbyeong",
    title: "새",
    titleOriginal: "새",
    poet: "천상병 (대한민국)",
    poetOriginal: "천상병",
    excerpt: "외롭게 사는 옥상 밑에서\n날아온 새 한 마리\n그놈은 창턱에 앉아\n조그만 눈으로 나를 본다\n\n나도 그놈을 본다\n\n우리는 서로 다정한 벗이다\n말은 없어도\n마음은 통하는……",
    whyRecommended: "외로움의 한가운데서 우연히 마주친 작은 날짐승과 나누는 무언의 따스한 연대와 위로입니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=560&subcontentid=34503",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "jiltuneun_naui_him",
    title: "질투는 나의 힘",
    titleOriginal: "질투는 나의 힘",
    poet: "기형도 (대한민국)",
    poetOriginal: "기형도",
    excerpt: "아주 오랜 세월이 흐른 뒤에\n힘없는 낱말들이 라일락 잎처럼 우거진 설운 날에\n외쳤을 것이다, 저 맑은 하늘 밑\n\n나를 한 번도 사랑하지 않았노라고\n\n기록할 만한 것은 오직 미열뿐이었노라고\n내 희망의 내용은 질투뿐이었노라고.",
    whyRecommended: "젊은 날의 방황과 자학, 인정욕구를 가차 없이 직시함으로써 진정한 자기 사랑의 첫걸음을 떼게 합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=610&subcontentid=38101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "binjip",
    title: "빈집",
    titleOriginal: "빈집",
    poet: "기형도 (대한민국)",
    poetOriginal: "기형도",
    excerpt: "사랑을 잃고 나는 쓰네\n\n잘 있거라, 짧았던 밤들아\n창밖을 떠돌던 겨울 안개들아\n아무것도 모르던 촛불들아, 잘 있거라\n공포를 기다리던 흰 종이들아\n망설임을 대신하던 눈물들아\n잘 있거라, 더 이상 내 것이 아닌 열망들아\n\n장님처럼 나 이제 더듬거리며 문을 잠그네\n가엾은 내 사랑 빈집에 갇혔네",
    whyRecommended: "이별의 잔해를 봉인하며 써 내려간 가장 서늘하고도 탐미적인 애도의 언어로 깊은 카타르시스를 줍니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=610&subcontentid=38102",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "eomma_geokjeong",
    title: "엄마 걱정",
    titleOriginal: "엄마 걱정",
    poet: "기형도 (대한민국)",
    poetOriginal: "기형도",
    excerpt: "열무 삼십 단을 이고\n시장에 간 우리 엄마\n안 오시네, 해는 시든 지 오래\n나는 찬밥처럼 방에 담겨\n아무리 천천히 숙제를 해도\n엄마 안 오시네, 배추잎 같은 발소리 타벅타벅\n안 들리네, 어둡고 무서워\n금간 창틈으로 고요히 빗소리\n빈방에 혼자 엎드려 훌쩍거리던\n\n아주 먼 옛날\n지금도 눈시울을 붉히게 하는\n내 유년의 윗목",
    whyRecommended: "유년 시절 어스름 속에서 어머니를 기다리던 시린 기억을 통해 그리움과 사랑의 원형을 소환합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=610&subcontentid=38103",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "galdae",
    title: "갈대",
    titleOriginal: "갈대",
    poet: "신경림 (대한민국)",
    poetOriginal: "신경림",
    excerpt: "언제부턴가 갈대는 속으로\n조용히 울고 있었다.\n그런 어느 밤이었을 것이다. 갈대는\n그의 온몸이 흔들리고 있는 것을 알았다.\n\n바람도 달빛도 아닌 것.\n갈대는 저를 흔드는 것이 제 조용한 울음인 것을\n까맣게 몰랐다.\n\n― 산다는 것은 속으로 이렇게\n조용히 울고 있는 것이란 것을\n그는 몰랐다.",
    whyRecommended: "타인이 아닌 내면의 슬픔으로 인해 흔들리는 인간 존재의 근원적 비애를 부드럽게 쓰다듬어 줍니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=630&subcontentid=39201",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "gananhan_sarang_norae",
    title: "가난한 사랑 노래",
    titleOriginal: "가난한 사랑 노래",
    poet: "신경림 (대한민국)",
    poetOriginal: "신경림",
    excerpt: "가난하다고 해서 외로움을 모르겠는가\n너와 헤어져 돌아오는\n눈 쌓인 골목길에 새파랗게 달빛이 쏟아지는데.\n\n가난하다고 해서 두려움이 없겠는가\n두 점을 치는 소리\n방범대원의 호각 소리 메밀묵 사는 소리에\n눈을 뜨면 멀리 찾아온 바람 소리.\n\n가난하다고 해서 그리움을 버렸겠는가\n어머님 보고 싶소 수없이 뇌어 보지만\n\n가난하다고 해서 왜 모르겠는가\n가난하기 때문에 이것들을\n이 모든 것들을 버려야 한다는 것을.",
    whyRecommended: "척박한 현실 속에서도 포기할 수 없는 인간의 온기와 사랑의 애틋함을 눈물겹게 옹호합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=630&subcontentid=39202",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "jeulgeoun_pyeonji",
    title: "즐거운 편지",
    titleOriginal: "즐거운 편지",
    poet: "황동규 (대한민국)",
    poetOriginal: "황동규",
    excerpt: "내 그대를 생각함은 항상 그대가 앉아 있는 배경에서 해가 지고 바람이 부는 일처럼 사소한 일일 것이나 언젠가 그대가 한없이 괴로움 속을 헤매일 때에 오랫동안 전해 오던 그 사소함으로 그대를 불러보리라.\n\n진실로 진실로 내가 그대를 사랑하는 까닭은 내 나의 사랑을 한없이 잇닿은 그 기다림으로 바꾸어 버린 데 있었다. 밤이 들면서 골짜기엔 눈이 퍼붓기 시작했다. 내 사랑도 어디쯤에선 반드시 그칠 것을 믿는다. 다만 그때 내 기다림의 자세를 생각하는 것뿐이다. 그동안에 눈이 그치고 꽃이 피어나고 낙엽이 떨어지고 또 눈이 퍼붓고 할 것을 믿는다.",
    whyRecommended: "자연의 해넘이처럼 사소하지만 영원히 지속되는 성숙한 기다림과 무조건적인 사랑을 고백합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=650&subcontentid=40501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "heundeullimyeo_pineun_kkot",
    title: "흔들리며 피는 꽃",
    titleOriginal: "흔들리며 피는 꽃",
    poet: "도종환 (대한민국)",
    poetOriginal: "도종환",
    excerpt: "흔들리지 않고 피는 꽃이 어디 있으랴\n이 세상 그 어떤 아름다운 꽃들도\n다 흔들리면서 피었나니\n흔들리면서 줄기를 곧게 세웠나니\n흔들리지 않고 가는 사랑이 어디 있으랴\n\n젖지 않고 피는 꽃이 어디 있으랴\n이 세상 그 어떤 빛나는 꽃들도\n다 젖으며 젖으며 피었나니\n바람과 비에 젖으며 꽃잎 따뜻하게 피웠나니\n젖지 않고 가는 삶이 어디 있으랴",
    whyRecommended: "살아가며 겪는 방황과 시련이 모두 아름다운 꽃을 피우기 위한 필연적 축복임을 다정하게 일깨웁니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2050&subcontentid=55102",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "damjaengi",
    title: "담쟁이",
    titleOriginal: "담쟁이",
    poet: "도종환 (대한민국)",
    poetOriginal: "도종환",
    excerpt: "저것은 벽\n어쩔 수 없는 벽이라고 우리가 느낄 때\n그때\n담쟁이는 말없이 그 벽을 오른다\n\n물 한 방울 없고 씨앗 한 톨 살아남을 수 없는\n저것은 절망의 벽이라고 말할 때\n담쟁이는 서두르지 않고 앞으로 나아간다\n\n한 됫박의 흙도 없는 바위를 껴안고\n한 잎의 푸른 잎으로 또 한 잎의 푸른 잎을 이끌고\n결국 그 벽을 넘는다",
    whyRecommended: "절망의 거대한 벽 앞에서도 여럿이 손을 잡고 끝내 푸르게 벽을 넘어서는 연대와 인내의 희망을 전합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2050&subcontentid=55105",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "pulgil",
    title: "풀꽃",
    titleOriginal: "풀꽃",
    poet: "나태주 (대한민국)",
    poetOriginal: "나태주",
    excerpt: "자세히 보아야\n예쁘다\n\n오래 보아야\n사랑스럽다\n\n너도 그렇다.",
    whyRecommended: "존재 자체로 존귀한 당신의 가치를 가장 다정하고 따뜻한 시선으로 발견해 주는 최고의 위로입니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2880&subcontentid=75012",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "haengbok",
    title: "행복",
    titleOriginal: "행복",
    poet: "나태주 (대한민국)",
    poetOriginal: "나태주",
    excerpt: "저녁 때\n돌아갈 집이 있다는 것\n\n힘들 때\n마음속으로 생각할 사람 있다는 것\n\n외로울 때\n혼자서 부를 노래 있다는 것.",
    whyRecommended: "거창한 성공이 아니라 일상의 소박한 쉼과 마음속 사람 하나로 가득 차는 행복의 비밀을 알려줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2880&subcontentid=75015",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "saneun_beop",
    title: "사는 법",
    titleOriginal: "사는 법",
    poet: "나태주 (대한민국)",
    poetOriginal: "나태주",
    excerpt: "그리운 날은 그림을 그리고\n쓸쓸한 날은 음악을 들었다\n\n그러고도 남는 날은\n너를 생각해야만 했다.",
    whyRecommended: "예술과 그리움으로 외로운 시간을 향기롭게 채워가는 다정하고 낭만적인 삶의 태도를 건넵니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2880&subcontentid=75018",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "suseonhwa-ege",
    title: "수선화에게",
    titleOriginal: "수선화에게",
    poet: "정호승 (대한민국)",
    poetOriginal: "정호승",
    excerpt: "울지 마라\n외로우니까 사람이다\n살아간다는 것은 외로움을 견디는 일이다\n\n공연히 오지 않는 전화를 기다리지 마라\n눈이 오면 눈길을 걸어가고\n비가 오면 빗길을 걸어가라\n\n갈대숲에서 가슴검은도요새도 너를 보고 있다\n가끔은 하느님도 외로워서 눈물을 흘리신다\n\n새들이 나뭇가지에 앉아 있는 것도 외로움 때문이고\n네가 물가에 앉아 있는 것도 외로움 때문이다\n\n산 그림자도 하루에 한 번씩 마을로 내려온다\n종소리도 외로워서 울려 퍼진다.",
    whyRecommended: "고독은 결핍이 아니라 인간 본연의 숙명임을 받아들일 때 찾아오는 담담하고 단단한 평화를 선물합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2100&subcontentid=56101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "naega_saranghaneun_saram",
    title: "내가 사랑하는 사람",
    titleOriginal: "내가 사랑하는 사람",
    poet: "정호승 (대한민국)",
    poetOriginal: "정호승",
    excerpt: "나는 그늘이 없는 사람을 사랑하지 않는다\n나는 그늘을 사랑하지 않는 사람을 사랑하지 않는다\n나는 한 그루 나무의 그늘이 된 사람을 사랑한다\n\n햇빛도 그늘이 있어야 맑고 눈이 부시다\n\n나는 눈물이 없는 사람을 사랑하지 않는다\n나는 눈물을 사랑하지 않는 사람을 사랑하지 않는다\n나는 한 방울 눈물이 된 사람을 사랑한다\n\n기쁨도 눈물이 있어야 온전하고 아름답다.",
    whyRecommended: "삶의 그늘과 눈물의 가치를 온전히 이해하는 사람만이 누릴 수 있는 깊은 연민과 포용의 사랑을 노래합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2100&subcontentid=56105",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "sansanjogak",
    title: "산산조각",
    titleOriginal: "산산조각",
    poet: "정호승 (대한민국)",
    poetOriginal: "정호승",
    excerpt: "룸비니에서 사 온\n흙으로 빚은 부처님이\n마룻바닥에 떨어져 산산조각이 났다\n\n팔은 팔대로 다리는 다리대로\n목은 목대로 부러져\n속상해서 울타리 밑에 버렸더니\n\n부처님이 깨진 채로 미소 지으며 말씀하셨다\n'산산조각이 나면\n산산조각을 얻을 수 있지\n산산조각이 나면\n산산조각으로 살아갈 수 있지'",
    whyRecommended: "인생의 기대와 꿈이 산산조각 나더라도 그 조각조각으로 다시 온전히 살아갈 수 있다는 거대한 구원의 지혜입니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2100&subcontentid=56108",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "neoege_munneunda",
    title: "너에게 묻는다",
    titleOriginal: "너에게 묻는다",
    poet: "안도현 (대한민국)",
    poetOriginal: "안도현",
    excerpt: "연탄재 함부로 발로 차지 마라\n\n너는\n\n누구에게 한 번이라도 뜨거운 사람이었느냐.",
    whyRecommended: "남을 위해 온몸을 다 바쳐 하얗게 불태워 본 적 있는가라는 뜨거운 물음으로 영혼의 열정을 지핍니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2200&subcontentid=58101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "uriga_nunbariramyeon",
    title: "우리가 눈발이라면",
    titleOriginal: "우리가 눈발이라면",
    poet: "안도현 (대한민국)",
    poetOriginal: "안도현",
    excerpt: "우리가 눈발이라면\n허공에서 쭈깃쭈깃 흩날리는\n진눈깨비는 되지 말자\n\n세상이 바람 불고 춥고 어둡다 해도\n사람이 사는 마을\n가장 낮은 곳으로\n따뜻한 함박눈이 되어 내리자\n\n잠 못 든 이의 창가에서는\n편지가 되고\n그이의 깊고 붉은 상처 위에 돋는\n새살이 되자.",
    whyRecommended: "춥고 어두운 세상일수록 가장 낮은 곳의 이웃을 포근히 감싸 안는 함박눈처럼 따뜻한 존재가 되자는 결의입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2200&subcontentid=58104",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "sapyeongyeog-eseo",
    title: "사평역에서",
    titleOriginal: "사평역에서",
    poet: "곽재구 (대한민국)",
    poetOriginal: "곽재구",
    excerpt: "막차는 좀처럼 오지 않았다\n대합실 밖에는 밤새 송이눈이 쌓이고\n흰 보라 수수꽃 눈시린 유리창마다\n톱밥난로가 지펴지고 있었다\n\n그믐처럼 서러운 알은 편자 하나씩을 귓전에 걸고\n그리웠던 순간들을 생각하며 나는\n한 줌의 톱밥을 불빛 속에 던져 주었다\n\n내면 깊숙이 할 말들은 가득해도\n청색의 손바닥을 불빛에 녹이며\n모두들 아무 말도 하지 않았다.",
    whyRecommended: "눈 내리는 밤 간이역 대합실 난로처럼, 차가운 세상의 외로움을 서로의 온기로 덥혀주는 아늑한 서정입니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2001&subcontentid=54001",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "joyonghage_gang-euro",
    title: "조용하게, 강으로, 그러다 흐르라",
    titleOriginal: "조용하게, 강으로, 그러다 흐르라",
    poet: "김용택 (대한민국)",
    poetOriginal: "김용택",
    excerpt: "사람들 속에서 조용하게, 강으로, 그러다 흐르라.\n물방울들이 모여 강이 되고\n강이 바다로 흘러가듯\n네 안의 맑은 샘을 믿으라.\n\n흔들림 속에서도\n너 자신의 길을 잃지 말라.",
    whyRecommended: "세상의 소란에 휩쓸리지 않고 내면의 맑은 물줄기를 따라 자연스럽게 대양으로 나아가는 지혜를 줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2515&subcontentid=69084",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "dali_tteotdago",
    title: "달이 떴다고 전화를 주시다니요",
    titleOriginal: "달이 떴다고 전화를 주시다니요",
    poet: "김용택 (대한민국)",
    poetOriginal: "김용택",
    excerpt: "달이 떴다고 전화를 주시다니요\n이 밤, 너무 신나고 근사해요\n\n내 마음에도 생전 처음 보는\n환한 달이 두둥실 떠올랐습니다\n\n올려다본 하늘엔 달이 가득하고\n내 귓가엔 당신 목소리가 가득합니다.",
    whyRecommended: "밤하늘의 달 하나만으로도 설레는 전화를 건넬 수 있는 맑고 순수한 사랑의 기쁨을 나눕니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2515&subcontentid=69088",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "geudaega_gyeot-e_isseodo",
    title: "그대가 곁에 있어도 나는 그대가 그립다",
    titleOriginal: "그대가 곁에 있어도 나는 그대가 그립다",
    poet: "류시화 (대한민국)",
    poetOriginal: "류시화",
    excerpt: "물속에는\n물만 있는 것이 아니다\n하늘에는\n그 하늘만 있는 것이 아니다\n그리고 내 안에는\n나만이 있는 것이 아니다\n\n내 안에 있는 그대 모습을\n내가 어떻게 숨기겠는가\n\n그대가 곁에 있어도\n나는 그대가 그립다.",
    whyRecommended: "사랑할수록 더 깊어지는 신비로운 그리움과 존재의 빈자리를 영적인 시선으로 보듬어 안습니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2700&subcontentid=71201",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "chinguya_neoneun_ani",
    title: "친구야 너는 아니",
    titleOriginal: "친구야 너는 아니",
    poet: "이해인 (대한민국)",
    poetOriginal: "이해인",
    excerpt: "꽃이 필 때처럼\n그렇게 조용히\n나에게 다가와 준 사람\n\n힘들 때마다\n묵묵히 곁을 지켜주며\n등을 토닥여 준 사람\n\n친구야 너는 아니\n네가 내 삶의 얼마나 큰 선물인지\n너의 맑은 눈빛 하나로\n세상이 얼마나 따뜻해지는지.",
    whyRecommended: "묵묵히 곁을 지켜주는 친구의 소중함과 따뜻한 우정의 고마움을 맑고 담백한 목소리로 전합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2600&subcontentid=70101",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "nunmureun_wae_jjanga",
    title: "눈물은 왜 짠가",
    titleOriginal: "눈물은 왜 짠가",
    poet: "함민복 (대한민국)",
    poetOriginal: "함민복",
    excerpt: "어머니는 깍두기 국물을 국밥에 부으시며\n'아가, 국물이 싱거우면 소금을 더 쳐라' 하셨다.\n어머니는 내 밥에 고기점을 얹어주시고\n당신은 멀건 국물만 드셨다.\n\n그날 이후 나는 안다.\n세상에서 가장 짠 눈물은 어머니의 사랑이라는 것을.",
    whyRecommended: "자식을 향한 어머니의 눈물겨운 희생과 지극한 사랑을 가장 진솔하고 가슴 뭉클하게 담아냅니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2750&subcontentid=72301",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "daechu_han_al",
    title: "대추 한 알",
    titleOriginal: "대추 한 알",
    poet: "장석주 (대한민국)",
    poetOriginal: "장석주",
    excerpt: "저게 저절로 붉어질 리는 없다.\n저 안에 태풍 몇 개\n저 안에 천둥 몇 개\n저 안에 벼락 몇 개\n저 안에 번개 몇 개가 들어 있어서\n붉게 익히는 것일 게다.\n\n저게 저 혼자 둥글어질 리는 없다.\n저 안에 무서리 내리는 몇 밤\n저 안에 땡볕 두어 달\n저 안에 초승달 몇 날이 들어서서\n둥글게 빚는 것일 게다.",
    whyRecommended: "대추 한 알 속에 우주의 온갖 비바람과 인내가 녹아있듯, 우리의 작은 성취 또한 온 우주가 빚어낸 결실임을 깨닫게 합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2800&subcontentid=73401",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "mokmwa_suknyeo",
    title: "목마와 숙녀",
    titleOriginal: "목마와 숙녀",
    poet: "박인환 (대한민국)",
    poetOriginal: "박인환",
    excerpt: "한 잔의 술을 마시고\n우리는 버지니아 울프의 생애와\n목마를 타고 떠난 숙녀의 옷자락을 이야기한다\n목마는 주인을 버리고 그저 방울 소리만 울리며\n가을 속으로 떠났다\n술병에서 별이 떨어진다\n상심한 별은 내 가슴에 가볍게 부서진다\n\n인생은 외롭지도 않고\n그저 잡지의 표지처럼 통속하거늘\n한탄을 한들 무엇하랴.",
    whyRecommended: "전후 도시의 우수와 낭만, 실존의 허무를 멋스럽게 승화한 모더니즘 시의 대표적 명작입니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=415&subcontentid=26201",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "kkeopdegineun_gara",
    title: "껍데기는 가라",
    titleOriginal: "껍데기는 가라",
    poet: "신동엽 (대한민국)",
    poetOriginal: "신동엽",
    excerpt: "껍데기는 가라.\n사월도 알맹이만 남고\n껍데기는 가라.\n\n껍데기는 가라.\n동학년 곰나루의, 그 아우성만 살고\n껍데기는 가라.\n\n그리하여, 다시\n껍데기는 가라.\n이곳에선, 두 가슴과 그곳을 내민\n아사달과 아사녀가\n중립의 초례청 앞에 서서\n부끄럼 빛내며\n맞절할지니\n껍데기는 가라.\n한라에서 백두까지\n향그러운 흙가슴만 남고\n그 모오든 쇠붙이는 가라.",
    whyRecommended: "모든 거짓과 허식의 껍데기를 벗어던지고 순수한 생명과 역사의 알맹이로 거듭나자는 우렁찬 외침입니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=460&subcontentid=28301",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "ireon_si",
    title: "이런 시(詩)",
    titleOriginal: "이런 시",
    poet: "이상 (대한민국)",
    poetOriginal: "이상",
    excerpt: "역사를 찢고 나온 사람처럼\n나는 날마다 너를 기다렸다.\n\n지나가던 바람이 내 뺨을 만지고 가고\n밤이면 별들이 창가에 내려앉았다.\n그래도 너는 오지 않았다.\n\n너의 그림자가 어스름을 타고 번져올 때\n나는 그것이 사랑인 줄 알았다.",
    whyRecommended: "천재 시인 이상의 기발한 파격 속에서도 심장을 울리는 순정한 기다림과 애틋한 감성을 만납니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=420&subcontentid=26501",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "geunali_omyeon",
    title: "그날이 오면",
    titleOriginal: "그날이 오면",
    poet: "심훈 (대한민국)",
    poetOriginal: "심훈",
    excerpt: "그날이 오면, 그날이 오면은\n삼각산이 일어나 더덩실 춤이라도 추고\n한강물이 뒤집혀 용솟음칠 그날이,\n이 목숨이 끊기기 전에 와 주기만 할진댄\n나는 밤하늘에 날으는 까마귀와 같이\n종로의 인경을 머리로 들이받아 울리오리다.\n두개골은 깨어져 산산조각이 나도\n기뻐서 죽사오매 오히려 무슨 한이 남으오리까.",
    whyRecommended: "염원하던 자유와 해방의 그날을 향한 온몸을 던지는 열망과 거대한 환희의 에너지를 뿜어냅니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=430&subcontentid=26801",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "dongjitdal_ginagin_bam",
    title: "동짓달 기나긴 밤을",
    titleOriginal: "동짓달 기나긴 밤을",
    poet: "황진이 (조선)",
    poetOriginal: "황진이",
    excerpt: "동짓달 기나긴 밤을 한 허리를 베어 내어\n춘풍 이불 아래 서리서리 넣었다가\n어론 님 오신 날 밤이여들 굽이굽이 펴리라.",
    whyRecommended: "시간이라는 무형의 개념을 칼로 베어 이불 속에 품겠다는 우리 문학사상 가장 황홀하고 관능적인 상상력입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=50&subcontentid=1201",
    poemSourceName: "한국 고전문학 시선",
  },
  {
    id: "mollaseo_jowayo",
    title: "몰라서 좋아요",
    titleOriginal: "몰라서 좋아요",
    poet: "오은 (대한민국)",
    poetOriginal: "오은",
    excerpt: "모르는 감정이 싹텄다\n몰라서 설레고\n몰라서 걸어가 보고 싶다\n\n모든 것을 다 알지 못하기에\n오늘의 내 걸음은 새롭고\n빛나는 비밀을 품고 있다.",
    whyRecommended: "자신만의 창작 방향을 선택할 용기와 긴 호흡을 일깨워 줍니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2355&subcontentid=63217",
    poemSourceName: "시요일 라이브러리",
  },
  {
    id: "beotimmogi_doeeojuda",
    title: "버팀목이 되어 주다",
    titleOriginal: "버팀목이 되어 주다",
    poet: "복효근 (대한민국)",
    poetOriginal: "복효근",
    excerpt: "태풍에 쓰러진 나무를 위하여\n다른 나무가 등을 대어 주었다\n비바람 지나간 뒤에도\n그들은 서로의 어깨를 겯고 서 있었다\n\n사랑이란 어쩌면\n서로의 기우뚱한 무게를 기꺼이 나누어 지는 일.",
    whyRecommended: "흔들리는 서로의 삶에 조용히 어깨를 내어주는 따스한 연대와 사랑의 온기를 전합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=2900&subcontentid=76101",
    poemSourceName: "시요일 라이브러리",
    origin: "korean",
    country: "대한민국",
  },

  // =========================================================================
  // 🌍 세계 명시(名詩) 보물선 컬렉션 (외국 명시 대거 수록)
  // =========================================================================
  {
    id: "world_rilke_autumn_day",
    title: "가을날 (Herbsttag)",
    titleOriginal: "Herbsttag",
    poet: "라이너 마리아 릴케 (오스트리아/독일)",
    poetOriginal: "Rainer Maria Rilke",
    excerpt: "주여, 때가 왔습니다. 지난여름은 참으로 위대했습니다.\n해시계 위에 당신의 그림자를 드리우시고\n들판 위에 바람을 놓아 주십시오.\n\n마지막 과일들이 무르익도록 명해 주시고,\n그들에게 이틀만 더 남국의 날을 베푸시어\n완성에 이르게 하시고, 독한 포도주 속에\n마지막 단맛이 스며들게 해주십시오.\n\n지금 집이 없는 사람은 이제 집을 짓지 않습니다.\n지금 혼자인 사람은 오래도록 홀로 남아\n깨어서 읽고, 긴 편지를 쓸 것이며,\n낙엽이 흩날릴 때 불안스레\n가로수 길을 이리저리 헤맬 것입니다.",
    whyRecommended: "지나간 계절의 풍요와 다가올 고독을 담담히 수용하며, 깊은 내면의 고요와 성찰의 시간으로 우리를 이끕니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80001",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "오스트리아/독일",
  },
  {
    id: "world_frost_road_not_taken",
    title: "가지 않은 길 (The Road Not Taken)",
    titleOriginal: "The Road Not Taken",
    poet: "로버트 프로스트 (미국)",
    poetOriginal: "Robert Frost",
    excerpt: "노란 숲 속에 두 갈래 길이 있었습니다.\n나는 두 길을 다 가지 못하는 것을 안타깝게 생각하면서,\n오랫동안 서서 한 쪽 길이 굽어 꺾여 내려간 데까지,\n바라다볼 수 있는 데까지 멀리 바라보았습니다.\n\n그리고 다른 길을 택했습니다, 똑같이 아름답고,\n아마 더 걸어야 할 길이라고 생각했기에.\n풀이 더 무성하고 발길을 기다리는 듯했으니까요.\n\n훗날에 훗날에 나는 어디선가\n한숨을 쉬며 이야기할 것입니다.\n숲 속에 두 갈래 길이 있었다고,\n그리고 나는 사람이 적게 간 길을 택하였노라고,\n그것 때문에 모든 것이 달라졌노라고.",
    whyRecommended: "타인의 시선이나 안락한 관습 대신, 나만의 미지의 길을 당당히 선택할 수 있는 창조적 용기를 불어넣습니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80002",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_frost_stopping_by_woods",
    title: "눈 내리는 저녁 숲가에 멈추어 서서",
    titleOriginal: "Stopping by Woods on a Snowy Evening",
    poet: "로버트 프로스트 (미국)",
    poetOriginal: "Robert Frost",
    excerpt: "이 숲이 뉘 숲인지 알 듯하다.\n그의 집은 마을에 있지만,\n눈 덮여가는 숲을 보느라\n내가 여기 멈춰 선 것을 그는 모르리라.\n\n내 어린 말은 이상히 여길 것이다,\n농가 하나 없는 곳에 멈추어 서다니.\n숲과 얼어붙은 호수 사이,\n한 해 중 가장 어두운 저녁에.\n\n숲은 어둡고 아름답고 깊으나,\n내게는 지켜야 할 약속이 있고,\n잠들기 전에 가야 할 먼 길이 있다,\n잠들기 전에 가야 할 먼 길이 있다.",
    whyRecommended: "고요한 눈 덮인 숲의 적막 속에서 일상의 책무와 인생의 묵묵한 순례길을 긍정하는 담담한 위안을 건넵니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80003",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_pushkin_if_life_deceives",
    title: "삶이 그대를 속일지라도 (Если жизнь тебя обманет)",
    titleOriginal: "Если жизнь тебя обманет",
    poet: "알렉산드르 푸시킨 (러시아)",
    poetOriginal: "Aleksandr Pushkin",
    excerpt: "삶이 그대를 속일지라도\n슬퍼하거나 노하지 말라!\n우울한 날들을 견디면\n믿으라, 기쁨의 날이 오리니.\n\n마음은 미래에 사는 것,\n현재는 한없이 슬픈 것.\n모든 것은 순간에 지나가고,\n지나간 것은 훗날 소중하게 되리니.",
    whyRecommended: "절망의 한복판에서도 조급함을 내려놓고, 시간의 흐름 속에 피어날 미래의 기쁨과 치유를 신뢰하게 합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80004",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "러시아",
  },
  {
    id: "world_neruda_poetry",
    title: "시가 내게로 왔다 (La Poesía)",
    titleOriginal: "La Poesía",
    poet: "파블로 네루다 (칠레)",
    poetOriginal: "Pablo Neruda",
    excerpt: "그리고 그 나이에... 시가 나를 찾아왔다.\n나는 모른다, 그게 어디서 왔는지,\n겨울에서인지 강에서인지.\n언제 어떻게 왔는지 나는 모른다.\n아니다, 그것은 목소리도 아니었고, 말도 아니었으며,\n침묵도 아니었다.\n\n어느 날 밤길에서, 나뭇가지 사이에서,\n돌연한 밤의 한가운데서,\n격렬한 불길 속에서 혹은 홀로 돌아오던 길에서\n불쑥 나를 불렀다.\n그것은 얼굴도 없는 존재였으나 나를 건드렸다.\n\n그때 나는 쓰기 시작했다, 어설프게,\n불확실하게, 맹목적으로...\n그리고 내 영혼 속에 순수한 무언가가 솟아올랐다,\n열병 혹은 잃어버린 날개처럼,\n나는 해독하기 시작했다, 그 불길을.",
    whyRecommended: "모든 창작자와 영혼에게 불현듯 찾아오는 순수한 예술적 계시와 심장의 고동을 마주하게 합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80005",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "칠레",
  },
  {
    id: "world_neruda_tonight_i_can_write",
    title: "오늘 밤 나는 가장 슬픈 시를 쓸 수 있다",
    titleOriginal: "Puedo escribir los versos más tristes esta noche",
    poet: "파블로 네루다 (칠레)",
    poetOriginal: "Pablo Neruda",
    excerpt: "오늘 밤 나는 가장 슬픈 시를 쓸 수 있다.\n예컨대 이렇게 쓴다.\n'밤하늘엔 별들이 부서지고,\n푸른 별들은 저 멀리서 떨고 있다.'\n\n밤바람은 공중을 맴돌며 노래한다.\n오늘 밤 나는 가장 슬픈 시를 쓸 수 있다.\n나는 그녀를 사랑했고, 때때로 그녀도 나를 사랑했다.\n\n사랑은 그토록 짧고, 망각은 그토록 길다.",
    whyRecommended: "이별의 아픔을 푸른 별과 밤바람의 서정으로 승화시킨 20세기 가장 위대한 사랑의 비가입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80006",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "칠레",
  },
  {
    id: "world_dickinson_hope_feathers",
    title: "희망은 날개 달린 것 ('Hope' is the thing with feathers)",
    titleOriginal: "'Hope' is the thing with feathers",
    poet: "에밀리 디킨슨 (미국)",
    poetOriginal: "Emily Dickinson",
    excerpt: "희망은 한 마리 새, 날개 달린 것,\n영혼의 횃대에 앉아\n가사 없는 노래를 부르네,\n결코 멈추는 법 없이.\n\n모진 바람 속에서도 그 소리 가장 달콤하게 들리고,\n그토록 많은 이의 가슴을 따뜻하게 지켜준\n작은 새를 당황케 하려면\n참으로 사나운 폭풍이어야 하리라.\n\n나는 가장 추운 땅에서도 그 노래를 들었고\n가장 낯선 바다 위에서도 들었네.\n하지만 아무리 절박한 순간에도\n그 새는 내게 빵 한 조각 청하지 않았네.",
    whyRecommended: "가장 혹독한 영혼의 겨울에도 어떤 대가 없이 우리 내면에 깃들어 지저귀는 불멸의 희망을 노래합니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80007",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_dickinson_stop_one_heart",
    title: "내가 만약 한 사람의 가슴앓이를 멈추게 할 수 있다면",
    titleOriginal: "If I can stop one heart from breaking",
    poet: "에밀리 디킨슨 (미국)",
    poetOriginal: "Emily Dickinson",
    excerpt: "내가 만약 한 사람의 가슴앓이를 멈추게 할 수 있다면,\n나의 삶은 결코 헛되지 않으리.\n\n내가 만약 누군가의 고통을 덜어주거나,\n어떤 상처를 가라앉혀 주거나,\n기진맥진한 작은 울새 한 마리를\n다시 둥지로 올려놓아 줄 수 있다면,\n\n나의 삶은 결코 헛되지 않으리.",
    whyRecommended: "거창한 성공 대신 작고 연약한 생명을 보듬는 소박한 연민이야말로 삶의 가장 숭고한 가치임을 일깨웁니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80008",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_goethe_wandrers_nachtlied",
    title: "방랑자의 밤노래 (Wandrers Nachtlied)",
    titleOriginal: "Wandrers Nachtlied",
    poet: "요한 볼프강 폰 괴테 (독일)",
    poetOriginal: "Johann Wolfgang von Goethe",
    excerpt: "모든 산봉우리에\n안식이 깃들고,\n모든 나뭇가지 끝에는\n숨결 하나\n느껴지지 않네.\n\n숲속의 작은 새들도 소리 없이 잠들었으니,\n조금만 기다려라,\n머지않아 그대 또한 쉬게 되리니.",
    whyRecommended: "대자연의 장엄한 정적 속에서 지친 영혼에게 찾아오는 궁극의 안식과 평화를 읊조립니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80009",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "독일",
  },
  {
    id: "world_baudelaire_albatros",
    title: "알바트로스 (L'Albatros)",
    titleOriginal: "L'Albatros",
    poet: "샤를 보들레르 (프랑스)",
    poetOriginal: "Charles Baudelaire",
    excerpt: "흔히 뱃사람들은 장난삼아\n거대한 알바트로스를 붙잡는다,\n깊은 바다 위를 미끄러지듯 떠가는 배를\n게으른 길동무처럼 뒤따르는 이 바다의 새를.\n\n갑판 위에 내려놓자마자,\n이 창공의 왕자들은 어색하고 수치스러워하며,\n가련하게도 커다란 하얀 날개를\n노처럼 양옆으로 질질 끈다.\n\n시인도 폭풍우를 넘나들고 사수를 비웃는\n이 구름 속의 왕자와 같아라,\n지상에 유배되어 야유를 받으니,\n그 거인의 날개가 걷는 것을 방해하는구나.",
    whyRecommended: "세속의 좁은 잣대에 갇힌 예술가와 고귀한 이상주의자들의 운명과 드넓은 영혼의 날개를 변호합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80010",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_rimbaud_sensation",
    title: "감각 (Sensation)",
    titleOriginal: "Sensation",
    poet: "아르튀르 랭보 (프랑스)",
    poetOriginal: "Arthur Rimbaud",
    excerpt: "여름날 푸른 저녁이면 오솔길을 가리라,\n보리 이삭에 찔리고, 잔디를 밟으며.\n꿈꾸듯 발걸음마다 신선함을 느끼리라.\n바람이 내 맨머리를 스치도록 내버려두리라.\n\n말도 하지 않으리라, 생각도 하지 않으리라.\n그러나 끝없는 사랑만이 내 영혼 속에 피어나리니,\n방랑자처럼 멀리 아주 멀리 떠나가리라,\n자연과 더불어, 여인과 함께 가는 것처럼 행복하게.",
    whyRecommended: "온갖 관념과 번뇌를 비워낸 뒤 오직 오감으로 자연과 우주를 껴안는 청춘의 눈부신 자유를 노래합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80011",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_verlaine_chanson_dautomne",
    title: "가을의 노래 (Chanson d'automne)",
    titleOriginal: "Chanson d'automne",
    poet: "폴 베를렌 (프랑스)",
    poetOriginal: "Paul Verlaine",
    excerpt: "가을날\n바이올린의\n긴 흐느낌,\n단조로운\n우수로\n내 가슴을 저미네.\n\n종소리 울릴 때\n가슴 메이고\n창백해져,\n옛 시절을\n눈물 흘리며\n회상하네.\n\n그리고 나는 떠나가네,\n휘몰아치는\n궂은 바람에\n이리저리 쓸리는\n낙엽처럼.",
    whyRecommended: "우수 어린 가을 선율처럼 섬세하게 스며드는 인간 존재의 무상함과 애틋한 서정의 극치를 보여줍니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80012",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_prevert_les_feuilles_mortes",
    title: "고엽 (Les Feuilles mortes)",
    titleOriginal: "Les Feuilles mortes",
    poet: "자크 프레베르 (프랑스)",
    poetOriginal: "Jacques Prévert",
    excerpt: "오, 그대가 기억하기를 얼마나 간절히 바라는가,\n우리가 다정했던 그 행복한 날들을.\n그때는 삶이 훨씬 아름다웠고,\n태양은 오늘보다 더 눈부시게 빛났었지.\n\n낙엽들이 삽으로 퍼담겨지네,\n추억과 회한도 그와 같이.\n북풍은 그 모든 것을 쓸어가네,\n망각의 차가운 밤 속으로.\n\n그러나 내게 그대는 노래하네,\n침묵 속에서도 결코 잊히지 않는 노래를.",
    whyRecommended: "지나간 찬란한 사랑의 기억을 낙엽의 낙하에 빗대어 담담하면서도 깊은 울림으로 회상하게 합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80013",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_wordsworth_daffodils",
    title: "수선화 (I Wandered Lonely as a Cloud)",
    titleOriginal: "I Wandered Lonely as a Cloud",
    poet: "윌리엄 워즈워스 (영국)",
    poetOriginal: "William Wordsworth",
    excerpt: "골짜기와 언덕 위를 높이 떠도는\n구름처럼 외로이 헤매다가,\n나는 문득 한 무리의 군중을 보았네,\n황금빛 수선화들의 환희에 찬 무리를.\n호숫가, 나무들 아래에서,\n미풍에 흔들거리며 춤추고 있었네.\n\n자주, 내가 자리에 누워\n공허하거나 수심에 잠겨 있을 때면,\n고독의 축복인 내면의 눈에\n그 수선화들이 번쩍 스치나니,\n그때 내 가슴은 기쁨으로 가득 차\n수선화들과 함께 춤을 추네.",
    whyRecommended: "외로움의 순간에도 마음에 저장된 자연의 찬란한 순간들이 되살아나 끝없는 환희를 베풀어 줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80014",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_wordsworth_rainbow",
    title: "무지개 (My Heart Leaps Up)",
    titleOriginal: "My Heart Leaps Up",
    poet: "윌리엄 워즈워스 (영국)",
    poetOriginal: "William Wordsworth",
    excerpt: "하늘의 무지개를 바라보면\n내 가슴은 뛰누나.\n나 어릴 때도 그러했고,\n어른이 된 지금도 그러하며,\n늙어서도 그러하리라,\n그렇지 않다면 차라리 죽는 게 나으리!\n\n아이는 어른의 아버지.\n바라건대 나의 하루하루가\n자연의 경건함으로 이어지기를.",
    whyRecommended: "어릴 적의 순수한 경이와 감동을 잃지 않고 평생토록 간직하려는 인간 영혼의 순결함을 되새깁니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80015",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_yeats_innisfree",
    title: "이니스프리 호수 섬 (The Lake Isle of Innisfree)",
    titleOriginal: "The Lake Isle of Innisfree",
    poet: "윌리엄 버틀러 예이츠 (아일랜드)",
    poetOriginal: "William Butler Yeats",
    excerpt: "나 이제 일어나 가리라, 이니스프리로 가리라.\n거기 흙과 욋가지로 작은 오두막을 짓고,\n아홉 이랑 콩밭과 꿀벌 통 하나를 두고,\n벌들 윙윙대는 숲속 빈터에 홀로 살리라.\n\n거기서 얼마쯤 평화를 맛보리라, 평화는 천천히 방울져 내리는 것,\n아침의 베일로부터 귀뚜라미 우는 곳으로 떨어지는 것.\n거기는 한밤도 온통 반짝이고, 한낮은 자줏빛 광채,\n저녁엔 방울새 날갯소리 가득한 곳.\n\n나 이제 일어나 가리라, 밤이나 낮이나\n호숫가에 찰랑이는 물결 소리 들려오나니.\n잿빛 포도 위에 서 있을 때나 길 위에 서 있을 때나,\n가슴 깊은 곳에서 그 물결 소리 듣노라.",
    whyRecommended: "도시의 소음과 피로에 지친 마음에 나만의 영원한 도피처이자 평화의 섬, 내면의 이니스프리를 선물합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80016",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "아일랜드",
  },
  {
    id: "world_yeats_cloths_of_heaven",
    title: "하늘의 융단 (Aedh Wishes for the Cloths of Heaven)",
    titleOriginal: "Aedh Wishes for the Cloths of Heaven",
    poet: "윌리엄 버틀러 예이츠 (아일랜드)",
    poetOriginal: "William Butler Yeats",
    excerpt: "내게 금빛과 은빛으로 짠\n하늘의 수놓은 융단이 있다면,\n어둠과 빛과 어스름으로 물들인\n파랗고 어스레하고 짙은 융단이 있다면,\n그 융단을 그대 발밑에 깔아 드리련만.\n\n그러나 나는 가난하여 가진 것은 오직 꿈뿐,\n그대 발밑에 내 꿈을 깔아 놓았으니,\n사뿐히 밟으소서, 그대 밟는 것 내 꿈이오니.",
    whyRecommended: "세상의 그 어떤 보물보다 진귀한 자신의 순수한 영혼과 꿈 전체를 연인에게 바치는 지고의 헌신입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80017",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "아일랜드",
  },
  {
    id: "world_gibran_on_love",
    title: "사랑에 대하여 (On Love)",
    titleOriginal: "On Love",
    poet: "칼릴 지브란 (레바논/미국)",
    poetOriginal: "Kahlil Gibran",
    excerpt: "사랑이 그대들을 부르거든 그를 따르라,\n비록 그 길이 험하고 가파를지라도.\n사랑의 날개가 그대들을 감싸 안거든 몸을 내맡기라,\n비록 그 깃털 속에 숨겨진 칼날이 상처를 입힐지라도.\n\n사랑은 그대들에게 왕관을 씌워주지만\n동시에 십자가에 못 박기도 하는 법.\n사랑은 그대들의 성장을 도우면서도\n동시에 가지를 쳐내어 단련시키는 법.\n\n사랑은 스스로를 온전히 내어줄 뿐 아무것도 요구하지 않으며,\n소유하지도 소유당하지도 않는 것,\n사랑은 오직 사랑으로 충만하기 때문입니다.",
    whyRecommended: "사랑의 환희뿐 아니라 시련과 단련까지도 영혼의 성숙으로 받아들이는 숭고한 통찰을 전합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80018",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "레바논/미국",
  },
  {
    id: "world_gibran_on_joy_and_sorrow",
    title: "기쁨과 슬픔에 대하여 (On Joy and Sorrow)",
    titleOriginal: "On Joy and Sorrow",
    poet: "칼릴 지브란 (레바논/미국)",
    poetOriginal: "Kahlil Gibran",
    excerpt: "그대의 기쁨은 가면을 벗은 슬픔일 뿐.\n그대의 눈물이 솟아오르는 바로 그 우물에서\n자주 그대의 웃음 또한 차오르는 법.\n\n슬픔이 그대의 존재를 깊이 파고들수록,\n그대가 담을 수 있는 기쁨의 양 또한 넓어지리라.\n\n기쁠 때 그대의 가슴속을 깊이 들여다보라,\n오직 그대에게 슬픔을 주었던 바로 그것이\n지금 기쁨을 주고 있음을 보게 되리라.\n슬플 때 다시 가슴속을 들여다보라,\n그대가 눈물짓는 것은 과거 한때 그대의 기쁨이었던 것 때문임을 보리라.",
    whyRecommended: "기쁨과 슬픔이 동전의 양면처럼 서로를 빚어내며 영혼의 그릇을 넓혀간다는 깊은 위안을 줍니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80019",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "레바논/미국",
  },
  {
    id: "world_hesse_im_nebel",
    title: "안개 속에서 (Im Nebel)",
    titleOriginal: "Im Nebel",
    poet: "헤르만 헤세 (독일/스위스)",
    poetOriginal: "Hermann Hesse",
    excerpt: "안개 속을 거니는 것은 참으로 이상하다!\n모든 덤불과 돌은 외롭고,\n어떤 나무도 다른 나무를 보지 못한다,\n모두가 홀로 있다.\n\n내 삶이 아직 밝았을 때\n세상은 벗들로 가득 차 있었으나,\n이제 안개가 내리덮이자\n아무도 더는 보이지 않는다.\n\n어둠을 알지 못하는 자는\n진실로 현명하다 할 수 없으리,\n어둠은 불가피하고 조용하게\n모든 것으로부터 그를 격리시킨다.\n\n안개 속을 거니는 것은 참으로 이상하다!\n산다는 것은 곧 외톨이가 되는 것,\n어떤 사람도 다른 사람을 알지 못한다,\n모두가 홀로 있다.",
    whyRecommended: "피할 수 없는 인간 존재의 근원적 고독을 정직하게 응시하며, 내면의 성숙과 지혜로 나아가게 합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80020",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "독일/스위스",
  },
  {
    id: "world_hesse_wandern",
    title: "방랑 (Wandern)",
    titleOriginal: "Wandern",
    poet: "헤르만 헤세 (독일/스위스)",
    poetOriginal: "Hermann Hesse",
    excerpt: "나무들이 속삭이는 소리를 들을 줄 아는 사람은\n삶의 가장 깊은 지혜를 배운다.\n나무는 나그네에게 말한다,\n‘조용히 서 있으라! 나를 보라!\n산다는 것은 쉬운 일이 아니다, 산다는 것은 어려운 일도 아니다.\n그것들은 신의 어린아이 같은 생각들일 뿐.’\n\n길은 어디로든 이어진다.\n너의 고향은 너의 가슴속에 있다,\n세상 그 어디에도 없다.",
    whyRecommended: "끊임없이 어디론가 떠도는 방랑자의 발걸음 속에서 진짜 고향은 내면의 중심에 있음을 깨우쳐 줍니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80021",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "독일/스위스",
  },
  {
    id: "world_rumi_guest_house",
    title: "여인숙 (The Guest House)",
    titleOriginal: "The Guest House",
    poet: "잘랄루딘 루미 (페르시아)",
    poetOriginal: "Jalal al-Din Rumi",
    excerpt: "인간이라는 존재는 하나의 여인숙과 같다.\n매일 아침 새로운 손님이 찾아온다.\n기쁨, 절망, 비열함,\n때로는 순간적인 깨달음이\n예상치 못한 방문객처럼 찾아온다.\n\n그들 모두를 환영하고 극진히 대접하라!\n설령 그들이 슬픔의 무리여서\n그대의 집을 난폭하게 휩쓸고 가구를 모두 치워버릴지라도,\n여전히 각 손님을 정성껏 모셔라.\n그는 어떤 새로운 기쁨을 위해\n그대의 방을 깨끗이 비워주는 것일지도 모른다.\n\n어두운 생각, 수치심, 악의를\n문가에서 웃으며 맞이하고 그들을 안으로 초대하라.\n누가 오든 감사히 여기라,\n그들 모두는 저 너머로부터\n그대의 길잡이로 보내진 것이기 때문이다.",
    whyRecommended: "찾아오는 모든 감정과 시련을 배척하지 않고 성장의 스승이자 신성한 손님으로 온전히 품어 안게 합니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80022",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "페르시아",
  },
  {
    id: "world_rumi_orchard_in_spring",
    title: "봄의 과수원으로 오세요",
    titleOriginal: "Come to the orchard in spring",
    poet: "잘랄루딘 루미 (페르시아)",
    poetOriginal: "Jalal al-Din Rumi",
    excerpt: "봄의 과수원으로 오세요.\n거기 빛과 석류꽃들이 있습니다.\n그대가 오시지 않는다면 이것들이 다 무슨 소용이겠습니까.\n그대가 오신다면 이것들이 다 무슨 소용이겠습니까.\n\n옳고 그름의 생각을 넘어서서\n저 들판이 있습니다.\n그곳에서 그대를 만나겠습니다.\n\n영혼이 그 풀밭에 누우면\n세상은 이야기하기에 너무 가득 차 있어,\n말도, 문장도, 심지어 '서로'라는 생각조차\n더는 아무런 의미가 없어집니다.",
    whyRecommended: "모든 분별과 시비, 언어의 한계를 뛰어넘어 영혼과 영혼이 완전한 하나 됨을 이루는 신비한 평온으로 이끕니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80023",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "페르시아",
  },
  {
    id: "world_blake_auguries_of_innocence",
    title: "순수의 전조 (Auguries of Innocence)",
    titleOriginal: "Auguries of Innocence",
    poet: "윌리엄 블레이크 (영국)",
    poetOriginal: "William Blake",
    excerpt: "한 알의 모래 속에서 세계를 보며\n한 송이 들꽃 속에서 천국을 보라.\n그대 손바닥 안에 무한을 쥐고\n한 시간 속에 영원을 품어라.\n\n새장 속의 지빠귀 한 마리는\n온 하늘을 분노케 하고,\n굶주림에 쓰러진 개 한 마리는\n국가의 몰락을 예고하리라.\n\n기쁨과 슬픔은 아름답게 엮어져\n거룩한 영혼을 감싸는 옷이 되나니.",
    whyRecommended: "일상의 가장 미세한 사물 속에서 우주의 무한성과 신성한 영원을 발견하는 신비주의적 통찰을 줍니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80024",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_tagore_mind_without_fear",
    title: "마음에 두려움이 없는 곳 (Where the Mind is Without Fear)",
    titleOriginal: "Where the Mind is Without Fear (Gitanjali 35)",
    poet: "라빈드라나트 타고르 (인도)",
    poetOriginal: "Rabindranath Tagore",
    excerpt: "마음에 두려움이 없고 머리는 높이 들리는 곳,\n지식이 자유로운 곳,\n세상이 좁다란 담벼락으로 쪼개어지지 않은 곳,\n말씀이 진리의 깊은 곳에서 솟아나는 곳,\n지칠 줄 모르는 노력이 완성을 향해 팔을 뻗는 곳,\n이성의 맑은 시냇물이 죽은 관습의 모래사막에 길을 잃지 않은 곳,\n끝없이 넓어지는 생각과 행동으로 마음이 이끌리는 곳,\n\n그 자유의 천국으로,\n나의 아버지여, 나의 조국이 깨어나게 하소서.",
    whyRecommended: "두려움을 이기고 영혼의 완전한 자유와 진리, 편견 없는 세계를 향해 나아가는 웅대한 기개를 불어넣습니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80025",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "인도",
  },
  {
    id: "world_tagore_stray_birds",
    title: "길 잃은 새들 (Stray Birds)",
    titleOriginal: "Stray Birds",
    poet: "라빈드라나트 타고르 (인도)",
    poetOriginal: "Rabindranath Tagore",
    excerpt: "여름의 길 잃은 새들이 내 창가에 찾아와 노래하고 날아간다.\n그리고 가을의 노란 잎들은 노래 없이 바람에 흩날린다.\n\n당신이 태양을 보지 못해 눈물 흘린다면,\n당신은 밤하늘의 별들마저 놓치게 되리라.\n\n모래가 조개껍질에게 묻는다, '너는 무엇을 감추고 있니?'\n조개껍질이 답한다, '침묵 속에 빚어낸 눈물 한 방울, 진주라오.'\n\n사랑은 그대에게서 아무것도 빼앗지 않고,\n오직 그대 자신을 완성시켜 주노라.",
    whyRecommended: "상실의 슬픔에 매몰되지 않고 밤하늘의 숨은 별과 조개의 진주 같은 아름다움을 발견하게 하는 잠언입니다.",
    theme: "comfort",
    themeLabel: "위로와 치유",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80026",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "인도",
  },
  {
    id: "world_whitman_o_captain",
    title: "오 캡틴! 나의 캡틴! (O Captain! My Captain!)",
    titleOriginal: "O Captain! My Captain!",
    poet: "월트 휘트먼 (미국)",
    poetOriginal: "Walt Whitman",
    excerpt: "오 캡틴! 나의 캡틴! 우리의 두려운 항해는 끝났습니다,\n배는 온갖 풍파를 이겨내고, 우리가 구하던 승리를 얻었습니다.\n항구는 가깝고, 종소리 들리며, 사람들은 모두 환호합니다,\n단단한 배의 용골을 바라보는 그들의 눈길은 엄숙하고 당당합니다.\n\n그러나 오 가슴이여! 가슴이여! 가슴이여!\n오 붉게 떨어지는 피 한 방울이여,\n갑판 위에는 나의 캡틴이 누워 계십니다,\n차갑게 숨을 거둔 채 누워 계십니다.",
    whyRecommended: "격변의 시대를 헤치고 승리를 이끌었으나 스러져간 영웅을 향한 숭고한 추모와 비장한 헌신을 노래합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80027",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_whitman_song_of_myself",
    title: "나 자신의 노래 (Song of Myself)",
    titleOriginal: "Song of Myself",
    poet: "월트 휘트먼 (미국)",
    poetOriginal: "Walt Whitman",
    excerpt: "나는 나 자신을 찬미하고 나 자신을 노래한다.\n내가 생각하는 것을 그대도 생각하리니,\n내게 속한 모든 원자가 그대에게도 고스란히 속해 있기 때문이다.\n\n나는 거닐며 내 영혼을 초대한다,\n나는 편안히 기대어 서서 여름 풀잎 한 포기를 관찰한다.\n내 혀, 내 피의 모든 원자는 이 흙, 이 공기에서 빚어졌으니.\n\n나는 크다, 나는 무수한 것들을 품고 있다.",
    whyRecommended: "우주와 하나로 연결된 자아의 거대한 존엄성과 생명력을 거침없이 선언하는 자유의 찬가입니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80028",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_keats_ode_to_nightingale",
    title: "나이팅게일에게 부치는 오드 (Ode to a Nightingale)",
    titleOriginal: "Ode to a Nightingale",
    poet: "존 키츠 (영국)",
    poetOriginal: "John Keats",
    excerpt: "내 가슴은 아프고, 나른한 마비가\n내 감각을 괴롭힌다, 마치 독미나리를 마신 듯.\n너의 행복을 시샘해서가 아니라,\n너의 행복에 너무나 겨운 탓이니,\n\n날개 달린 숲의 요정인 네가,\n너도밤나무의 푸른 잎과 헤아릴 수 없는 그림자 속에서\n목청껏 여름을 찬미하며 노래하고 있기 때문이다.\n\n너는 죽기 위해 태어난 것이 아니니, 불멸의 새여!\n굶주린 세대들도 너를 짓밟지 못하리니,\n이 덧없는 밤에 내가 듣고 있는 목소리는\n아주 오랜 옛날 황제와 농부들도 들었던 바로 그 소리.",
    whyRecommended: "유한한 인간의 고통을 넘어 영원히 불멸하는 예술과 자연의 아름다움에 가닿고자 하는 낭만주의의 정수입니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80029",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_shelley_ode_to_west_wind",
    title: "서풍의 노래 (Ode to the West Wind)",
    titleOriginal: "Ode to the West Wind",
    poet: "퍼시 비시 셸리 (영국)",
    poetOriginal: "Percy Bysshe Shelley",
    excerpt: "오 거친 서풍이여, 가을의 숨결이여!\n너 보이지 않는 존재 앞에 죽은 잎새들은 몰려가니,\n마치 마법사를 피해 달아나는 유령들처럼...\n\n나를 너의 하프로 만들어 다오, 숲이 그러하듯!\n내 잎새 떨어진들 어떠하랴, 숲이 그러하듯!\n너의 거대한 조화의 소용돌이는\n깊은 가을의 음조를 낳으리니, 슬프지만 감미롭구나.\n\n내 시를 온 인류 속에 흩뿌려 다오,\n꺼지지 않은 화로의 재와 불꽃처럼!\n나의 입술을 통해 잠자는 대지 위에\n예언의 나팔 소리를 울려 퍼지게 하라!\n\n오, 바람이여, 겨울이 오면 봄이 어찌 멀었으리요?",
    whyRecommended: "절체절명의 시련과 혹한 속에서도 머지않아 도래할 부활과 봄날의 찬가를 온몸으로 외치는 불멸의 명구입니다.",
    theme: "hope",
    themeLabel: "희망과 용기",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80030",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_tennyson_ulysses",
    title: "율리시스 (Ulysses)",
    titleOriginal: "Ulysses",
    poet: "알프레드 테니슨 (영국)",
    poetOriginal: "Alfred Tennyson",
    excerpt: "쉬는 것은 썩는 것, 반짝이려면 쓰여야 하는 것!\n숨만 쉰다고 삶이라 할 수 있으랴?\n삶 위에 삶이 겹친다 해도 너무 짧거늘,\n내게 남은 시간은 얼마 되지 않는다.\n\n나의 벗들이여, 결코 늦지 않았다, 새로운 세계를 찾아 나서기에는.\n배를 띄워라, 열을 맞추어 노를 저어라,\n울려 퍼지는 파도를 가르며 나아가자.\n나의 목적은 해 지는 곳을 넘어,\n모든 서쪽 별들이 잠기는 곳까지 항해하는 것,\n내가 죽을 때까지.\n\n비록 옛날 천지를 뒤흔들던 힘은 잃었을지라도,\n우리는 우리다.\n영웅적 기백을 품은 하나의 마음으로,\n시간과 운명에 의해 쇠약해졌을지라도 의지만은 굳세어,\n분투하고, 추구하며, 발견하고, 결코 굴복하지 않으리라.",
    whyRecommended: "생의 마지막 순간까지 안주하지 않고 미지의 바다를 향해 돛을 올리는 불굴의 인간 의지를 노래합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80031",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "영국",
  },
  {
    id: "world_valery_cimetiere_marin",
    title: "해변의 묘지 (Le Cimetière marin)",
    titleOriginal: "Le Cimetière marin",
    poet: "폴 발레리 (프랑스)",
    poetOriginal: "Paul Valéry",
    excerpt: "바람이 분다!... 살려고 애써야 한다!\n세찬 대기는 내 책을 열었다 닫고,\n물결은 부서져 바위로부터 솟구친다!\n날아가라, 온통 눈부신 책장들이여!\n부수어라, 파도여! 환희에 찬 물살로 부수어라,\n돛단배가 먹이를 쪼던 이 고요한 지붕을!\n\n바람이 분다!... 우리는 살아야만 한다.",
    whyRecommended: "지적 허무와 정적을 깨부수고 몰아치는 바닷바람 속에서 생의 치열한 호흡과 창조적 실존을 결단합니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80032",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_poe_annabel_lee",
    title: "애너벨 리 (Annabel Lee)",
    titleOriginal: "Annabel Lee",
    poet: "에드거 앨런 포 (미국)",
    poetOriginal: "Edgar Allan Poe",
    excerpt: "그것은 여러 해 전,\n바닷가 어느 왕국에서의 일이었다.\n그대 알지도 모를 한 소녀가 살았으니,\n그 이름은 애너벨 리였다.\n\n이 소녀는 날 사랑하고 내 사랑을 받는 것 외엔\n다른 아무 생각 없이 살았다.\n그녀도 어렸고 나 역시 어렸지만,\n바닷가 그 왕국에서,\n우리는 사랑 이상의 사랑으로 사랑했다,\n나와 나의 애너벨 리는.\n\n천국의 날개 달린 세라핌 천사들조차\n그녀와 나를 시샘할 정도였다.\n\n달도 내가 아름다운 애너벨 리의 꿈을 꾸지 않고는 비추지 않으며,\n별들도 떠오르면 나는 아름다운 애너벨 리의 밝은 눈을 본다.\n그리하여 나는 밤새도록 곁에 눕는다,\n내 사랑, 내 사랑, 나의 생명, 나의 신부 곁에,\n거기 바닷가 그녀의 무덤에,\n파도 소리 철썩이는 바닷가 그녀의 무덤에.",
    whyRecommended: "죽음마저 갈라놓을 수 없는 영원불멸의 지고한 사랑과 바닷가 파도 소리처럼 스며드는 환상적 애가를 읊조립니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80033",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "미국",
  },
  {
    id: "world_apollinaire_mirabeau",
    title: "미라보 다리 (Le Pont Mirabeau)",
    titleOriginal: "Le Pont Mirabeau",
    poet: "기욤 아폴리네르 (프랑스)",
    poetOriginal: "Guillaume Apollinaire",
    excerpt: "미라보 다리 아래 센 강은 흐르고\n우리들의 사랑도 흘러내린다\n내 마음속 깊이 기억하리니\n기쁨은 언제나 슬픔 뒤에 왔어라\n\n종이 울리고 밤이 찾아와도\n세월은 흐르고 나는 남는다\n\n손에 손을 맞잡고 얼굴을 마주보자\n우리들 팔의 다리 아래로\n영원의 눈길을 한 지친 물결이\n지나가는 동안\n\n사랑이 흘러간다 이 물결처럼\n사랑이 흘러간다\n어쩌면 이토록 삶은 느리고\n어쩌면 이토록 희망은 격렬한가\n\n날이 가고 달이 가도\n지나간 시간도 사랑도 다시 오지 않네\n미라보 다리 아래 센 강만 흐를 뿐.",
    whyRecommended: "흐르는 강물처럼 덧없이 흘러가는 사랑과 세월, 그러나 그 안에서도 꺼지지 않는 격렬한 희망을 담담히 노래합니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80034",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "프랑스",
  },
  {
    id: "world_heine_song_wings",
    title: "노래의 날개 위에 (Auf Flügeln des Gesanges)",
    titleOriginal: "Auf Flügeln des Gesanges",
    poet: "하인리히 하이네 (독일)",
    poetOriginal: "Heinrich Heine",
    excerpt: "노래의 날개 위에,\n내 사랑아, 너를 싣고 가리라,\n갠지스강 피어나는 들판으로,\n내가 아는 가장 아름다운 곳으로.\n\n거기엔 붉게 물든 꽃밭이\n고요한 달빛 아래 쉬고 있고,\n연꽃들은 다정한 자매를 기다리듯\n꽃잎을 열고 기다리누나.\n\n제비꽃들은 방싯대며 별들을 올려다보고,\n장미들은 은밀히 향기로운 귓속말을 나누고,\n온순하고 영리한 가젤들은 뛰어와 귀를 기울이네.\n\n그곳 종려나무 아래에 누워\n사랑과 안식을 마시며,\n우리는 축복받은 꿈을 꾸리라.",
    whyRecommended: "멘델스존의 선율로도 영원히 살아 숨 쉬는, 지상의 고단을 잊고 사랑의 낙원으로 날아오르는 황홀한 시정입니다.",
    theme: "love",
    themeLabel: "사랑과 그리움",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80035",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "독일",
  },
  {
    id: "world_machado_no_hay_camino",
    title: "나그네요, 길은 없다네 (Caminante, no hay camino)",
    titleOriginal: "Caminante, no hay camino",
    poet: "안토니오 마차도 (스페인)",
    poetOriginal: "Antonio Machado",
    excerpt: "나그네요, 그대의 발자국만이 길일 뿐,\n그 외에 다른 길은 없다네.\n나그네요, 길이란 처음부터 있는 것이 아니라네,\n걸어가면서 비로소 길이 만들어지는 것.\n\n걸어가면서 길을 만들고,\n뒤를 돌아보면\n다시는 밟을 수 없는 발자국 길이 보일 뿐.\n\n나그네요, 길은 없다네,\n오직 바다 위에 이는 물거품만이 있을 뿐.",
    whyRecommended: "누군가 닦아놓은 길을 좇지 않고 오직 자신의 발걸음으로 삶의 궤적을 개척해 나가는 구도자적 용기를 북돋웁니다.",
    theme: "courage",
    themeLabel: "열정과 기개",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80036",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "스페인",
  },
  {
    id: "world_pessoa_keeper_of_flocks",
    title: "시골뜨기의 노래 (O Guardador de Rebanhos)",
    titleOriginal: "O Guardador de Rebanhos",
    poet: "페르난두 페소아 (포르투갈)",
    poetOriginal: "Fernando Pessoa",
    excerpt: "나는 자연을 사랑한다, 내가 꽃을 바라볼 때\n꽃에 대해 생각하지 않기 때문이다.\n나는 꽃을 그저 꽃으로 바라본다.\n\n사물의 유일한 내적 의미는\n그것들에게 아무런 내적 의미가 없다는 데 있다.\n사물들은 존재할 뿐이다.\n\n꽃이 피는 것은 필연이 아니라 아름다움이며,\n강물이 흐르는 것은 어딘가에 도달하기 위해서가 아니라\n흐르는 것 그 자체이기 때문이다.\n\n나는 행복하다, 내가 아무것도 바라지 않고\n오직 존재하는 모든 것을 있는 그대로 바라보며 느끼기 때문이다.",
    whyRecommended: "지나친 해석과 집착을 내려놓고 사물과 생명이 지닌 본연의 순수한 존재감을 맑게 마주하게 합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80037",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "포르투갈",
  },
  {
    id: "world_basho_old_pond",
    title: "오래된 연못 (古池や)",
    titleOriginal: "古池や 蛙飛びこむ 水の音",
    poet: "마쓰오 바쇼 (일본)",
    poetOriginal: "Matsuo Basho",
    excerpt: "오래된 연못이여\n개구리 뛰어드는\n물소리 퐁당.\n\n고요함이여,\n바위에 스며드는\n매미의 울음소리.\n\n길 떠나는 자여,\n첫 서리에 젖는 삿갓을 쓰고\n가을바람을 벗 삼네.",
    whyRecommended: "찰나의 소리와 깊은 적막이 맞닿는 순간, 동양적 선(禪)의 미학과 무한한 여백의 평화를 경험하게 합니다.",
    theme: "nature",
    themeLabel: "자연과 평온",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80038",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "일본",
  },
  {
    id: "world_paz_epitaph",
    title: "시인의 묘비명 (Epitafio sobre ninguna tumba)",
    titleOriginal: "Epitafio sobre ninguna tumba",
    poet: "옥타비오 파스 (멕시코)",
    poetOriginal: "Octavio Paz",
    excerpt: "나는 멈추지 않았다, 걷고 또 걸었다.\n돌을 만졌고 바람의 숨결을 들이마셨다.\n나는 말을 사랑했고 침묵을 배웠다.\n\n빛은 시간을 만들고,\n시간은 기억을 만들며,\n기억은 마침내 한 줄기 시가 된다.\n\n내가 남긴 것은 아무것도 없다,\n오직 그대 가슴속에 일렁이는\n한 줌의 투명한 떨림 외에는.",
    whyRecommended: "라틴 아메리카의 마술적 언어로 삶과 기억, 침묵이 빚어내는 투명한 영혼의 울림을 전합니다.",
    theme: "reflection",
    themeLabel: "자아와 성찰",
    siyoilUrl: "https://www.siyoillib.com/PoemViewer?contentid=4000&subcontentid=80039",
    poemSourceName: "세계 명시 보물선",
    origin: "world",
    country: "멕시코",
  },
];
